package:
  name: behresp
  version: 0.0.0

requirements:
  build:
    - python
    - "taxcalc>=3.1.0"
    - pytest

  run:
    - python
    - "taxcalc>=3.1.0"
    - pytest

test:
  imports:
    - behresp

about:
  home: https://github.com/PSLmodels/Behavioral-Response
